# Generated by Django 4.0.4 on 2022-04-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_sponsor',
            old_name='Sponsor',
            new_name='sponsor',
        ),
        migrations.RenameField(
            model_name='student_sponsor',
            old_name='Student',
            new_name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='sponsor',
            field=models.ManyToManyField(blank=True, through='app.Student_sponsor', to='app.sponsor'),
        ),
    ]
