# Generated by Django 4.0.4 on 2022-04-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sponsor_is_legal_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sponsor',
        ),
    ]
