# Generated by Django 4.0.4 on 2022-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='spent_money',
        ),
        migrations.RemoveField(
            model_name='student',
            name='allocated_money',
        ),
        migrations.AddField(
            model_name='student',
            name='sponsor',
            field=models.ManyToManyField(blank=True, through='app.Student_sponsor', to='app.sponsor'),
        ),
        migrations.AlterField(
            model_name='student_sponsor',
            name='spent_money',
            field=models.IntegerField(),
        ),
    ]
