# Generated by Django 4.0.4 on 2022-04-22 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_sponsor_spent_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='spent_money',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='student',
            name='allocated_money',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
